/**
 * /api/applications/route.js  (UPDATED)
 * ─────────────────────────────────────────────────────────────────────────────
 * Changes from original:
 *  - POST now accepts optional `autoGenerate` flag → calls applicationGenerator.
 *  - POST now accepts optional `useAI` flag → calls aiService.improveDraft
 *    after generation (or on existing content if provided directly).
 *  - GET: added `status` filter param for review dashboards.
 *  - All original behaviour preserved when flags are not set.
 * ─────────────────────────────────────────────────────────────────────────────
 */
import { withAuth, apiSuccess, apiError } from "@/lib/api";
import connectDB from "@/lib/db";
import Application from "@/models/Application";
import Case from "@/models/Case";
import { generateApplication } from "@/lib/generators/applicationGenerator";
import { improveDraft } from "@/lib/ai/aiService";

// ─── GET /api/applications ────────────────────────────────────────────────────
export const GET = withAuth(async (request, context, user) => {
  try {
    await connectDB();

    const { searchParams } = new URL(request.url);
    const page = parseInt(searchParams.get("page") || "1");
    const limit = parseInt(searchParams.get("limit") || "10");
    const type = searchParams.get("type") || "";
    const status = searchParams.get("status") || ""; // ← NEW filter

    const query = { userId: user.id };
    if (type) query.applicationType = type;
    if (status) query.status = status;

    const total = await Application.countDocuments(query);
    const applications = await Application.find(query)
      .populate("caseId", "caseTitle caseNumber courtName")
      .sort({ createdAt: -1 })
      .skip((page - 1) * limit)
      .limit(limit);

    return apiSuccess({
      applications,
      total,
      page,
      totalPages: Math.ceil(total / limit),
    });
  } catch {
    return apiError("Failed to fetch applications.", 500);
  }
});

// ─── POST /api/applications ───────────────────────────────────────────────────
export const POST = withAuth(async (request, context, user) => {
  try {
    await connectDB();

    const body = await request.json();

    // Destructure control flags from body (they are not stored in DB directly)
    const {
      autoGenerate = false, // if true → run template generator
      useAI = false, // if true → run AI improvement layer
      ...applicationData
    } = body;

    // ── Step 1: Auto-fill from linked Case ──────────────────────────────────
    let caseData = {};
    if (applicationData.caseId) {
      const foundCase = await Case.findOne({
        _id: applicationData.caseId,
        userId: user.id,
      });
      if (foundCase) {
        caseData = {
          caseTitle: foundCase.caseTitle,
          caseNumber: foundCase.caseNumber || foundCase.suitNo,
          firNo: foundCase.firNo,
          courtName: foundCase.courtName,
          courtType: foundCase.courtType,
          ppcSections: foundCase.provisions || [],
          judgeName: foundCase.judgeName,
          applicantName: foundCase.clientName,
        };
      }
    }

    // Merge: case data < body data (body overrides case defaults)
    const mergedData = { ...caseData, ...applicationData };

    // ── Step 2: Template Generation ──────────────────────────────────────────
    let generatedContent = mergedData.content || mergedData.generatedText || "";
    let wasAutoGenerated = false;
    let status = mergedData.status || "draft";

    if (autoGenerate) {
      const genResult = generateApplication({
        type: mergedData.applicationType,
        data: mergedData,
      });

      if (!genResult.ok) {
        return apiError(`Template generation failed: ${genResult.error}`, 422);
      }

      generatedContent = genResult.content;
      wasAutoGenerated = true;
      status = "generated";
    }

    // ── Step 3: AI Enhancement ───────────────────────────────────────────────
    let aiEnhanced = false;
    let aiEnhancedAt = undefined;

    if (useAI && generatedContent) {
      const aiResult = await improveDraft(generatedContent);

      if (aiResult.ok) {
        generatedContent = aiResult.improvedContent;
        aiEnhanced = true;
        aiEnhancedAt = new Date();
      } else {
        // AI failure is non-fatal: log it, continue with un-enhanced content.
        console.warn(
          "[POST /api/applications] AI improvement skipped:",
          aiResult.error,
        );
      }
    } else if (useAI && !generatedContent) {
      return apiError(
        "useAI requires content to improve. Provide content or enable autoGenerate.",
        422,
      );
    }

    // ── Step 4: Persist ──────────────────────────────────────────────────────
    const application = await Application.create({
      ...mergedData,
      userId: user.id,
      content: generatedContent,
      generatedText: generatedContent, // keep legacy field in sync
      status,
      autoGenerated: wasAutoGenerated,
      aiEnhanced,
      aiEnhancedAt,
    });

    return apiSuccess({ application }, 201);
  } catch (error) {
    console.error("[POST /api/applications]", error);
    return apiError(error.message || "Failed to create application.", 500);
  }
});
