
import { withAuth, apiSuccess, apiError } from "@/lib/api";
import connectDB from "@/lib/db";
import Application from "@/models/Application";
import Case from "@/models/Case";
import { generateApplication } from "@/lib/generators/applicationGenerator";
import { improveDraft } from "@/lib/ai/aiService";

// --- GET /api/applications ---
export const GET = withAuth(async (request, context, user) => {
  try {
    await connectDB();

    const { searchParams } = new URL(request.url);
    const page = parseInt(searchParams.get("page") || "1");
    const limit = parseInt(searchParams.get("limit") || "10");
    const type = searchParams.get("type") || "";
    const status = searchParams.get("status") || "";

    const isSenior = user.seniority === "senior" || user.role === "admin";

    let query;
    if (isSenior) {

      query = status ? { status } : { userId: user.id };
    } else {
      query = { userId: user.id };
      if (status) query.status = status;
    }

    if (type) query.applicationType = type;

    const total = await Application.countDocuments(query);
    const applications = await Application.find(query)
      .populate("caseId", "caseTitle caseNumber courtName")
      .sort({ createdAt: -1 })
      .skip((page - 1) * limit)
      .limit(limit);

    return apiSuccess({
      applications,
      total,
      page,
      totalPages: Math.ceil(total / limit),
    });
  } catch {
    return apiError("Failed to fetch applications.", 500);
  }
});

// --- POST /api/applications ---
export const POST = withAuth(async (request, context, user) => {
  try {
    await connectDB();

    const body = await request.json();

    const {
      autoGenerate = false, 
      useAI = false, 
      ...applicationData
    } = body;

    let caseData = {};
    if (applicationData.caseId) {
      const foundCase = await Case.findOne({
        _id: applicationData.caseId,
        userId: user.id,
      });
      if (foundCase) {
        caseData = {
          caseTitle: foundCase.caseTitle,
          caseNumber: foundCase.caseNumber || foundCase.suitNo,
          firNo: foundCase.firNo,
          courtName: foundCase.courtName,
          courtType: foundCase.courtType,
          ppcSections: foundCase.provisions || [],
          judgeName: foundCase.judgeName,
          applicantName: foundCase.clientName,
        };
      }
    }

    const mergedData = { ...caseData, ...applicationData };

    let generatedContent = mergedData.content || mergedData.generatedText || "";
    let wasAutoGenerated = false;
    let status = mergedData.status || "draft";

    if (autoGenerate) {
      const genResult = generateApplication({
        type: mergedData.applicationType,
        data: mergedData,
      });

      if (!genResult.ok) {
        return apiError(`Template generation failed: ${genResult.error}`, 422);
      }

      generatedContent = genResult.content;
      wasAutoGenerated = true;
      status = "generated";
    }

    let aiEnhanced = false;
    let aiEnhancedAt = undefined;

    if (useAI && generatedContent) {
      const aiResult = await improveDraft(generatedContent);

      if (aiResult.ok) {
        generatedContent = aiResult.improvedContent;
        aiEnhanced = true;
        aiEnhancedAt = new Date();
      } else {
        console.warn(
          "[POST /api/applications] AI improvement skipped:",
          aiResult.error,
        );
      }
    } else if (useAI && !generatedContent) {
      return apiError(
        "useAI requires content to improve. Provide content or enable autoGenerate.",
        422,
      );
    }

    const application = await Application.create({
      ...mergedData,
      userId: user.id,
      content: generatedContent,
      generatedText: generatedContent, // keep legacy field in sync
      status,
      autoGenerated: wasAutoGenerated,
      aiEnhanced,
      aiEnhancedAt,
    });

    return apiSuccess({ application }, 201);
  } catch (error) {
    console.error("[POST /api/applications]", error);
    return apiError(error.message || "Failed to create application.", 500);
  }
});
