/**
 * Application.js  (UPDATED MODEL)
 * ─────────────────────────────────────────────────────────────────────────────
 * Changes from original:
 *  - Added `civil_suit` to applicationType enum (new template added).
 *  - Added `content` field: the canonical text (replaces generatedText ambiguity).
 *  - Kept `generatedText` as an alias for backward-compat (virtual getter).
 *  - Status enum extended: draft | generated | review | approved | filed.
 *  - Added `version` for future revision history.
 *  - Added `aiEnhanced` flag + `aiEnhancedAt` timestamp.
 *  - Added `autoGenerated` flag to track whether template was used.
 *  - Added `reviewNote` for senior lawyer feedback.
 *  - All original fields preserved unchanged.
 * ─────────────────────────────────────────────────────────────────────────────
 */
import mongoose from "mongoose";

const applicationSchema = new mongoose.Schema(
  {
    userId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true,
    },
    caseId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Case",
    },

    // Application type — extended with civil_suit
    applicationType: {
      type: String,
      required: true,
      enum: [
        "post_arrest_bail",
        "pre_arrest_bail",
        "civil_suit", // ← NEW
        "adjournment",
        "exemption",
        "placement_of_documents",
        "substitute_witness",
        "miscellaneous",
      ],
    },

    // ── Case metadata (auto-filled from linked case or manually entered) ──
    caseTitle: { type: String, trim: true },
    caseNumber: { type: String, trim: true },
    firNo: { type: String, trim: true },
    courtName: { type: String, trim: true },
    courtType: { type: String, trim: true },
    applicantName: { type: String, trim: true },
    respondentName: { type: String, trim: true },
    ppcSections: [{ type: String, trim: true }],
    judgeName: { type: String, trim: true },
    hearingDate: { type: Date },

    // ── Application-specific content ──────────────────────────────────────
    grounds: [{ type: String, trim: true }],
    prayer: { type: String, trim: true },
    additionalNotes: { type: String, trim: true },

    // ── Generated / edited text ───────────────────────────────────────────
    // `content` is the canonical field going forward.
    // Legacy `generatedText` is kept for backward compatibility.
    content: { type: String },
    generatedText: { type: String }, // kept for backward compat

    // ── Workflow metadata ─────────────────────────────────────────────────
    status: {
      type: String,
      enum: ["draft", "generated", "review", "approved", "filed"],
      default: "draft",
    },

    // Version counter — increment on each AI improvement or manual edit.
    // Useful for future diff/history feature.
    version: {
      type: Number,
      default: 1,
    },

    // Whether the template generator was used to create the initial draft.
    autoGenerated: {
      type: Boolean,
      default: false,
    },

    // Whether AI has improved this draft at least once.
    aiEnhanced: {
      type: Boolean,
      default: false,
    },

    aiEnhancedAt: {
      type: Date,
    },

    // Senior lawyer review feedback
    reviewNote: {
      type: String,
      trim: true,
    },

    // Senior lawyer who approved/reviewed (ref to User)
    reviewedBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
    },

    reviewedAt: {
      type: Date,
    },
  },
  { timestamps: true },
);

// ── Indexes ───────────────────────────────────────────────────────────────────
applicationSchema.index({ userId: 1, createdAt: -1 });
applicationSchema.index({ caseId: 1 });
applicationSchema.index({ status: 1 }); // for review dashboards
applicationSchema.index({ applicationType: 1 }); // for filtered listings

export default mongoose.models.Application ||
  mongoose.model("Application", applicationSchema);
